import os
import json
import numpy as np
from typing import List, Dict, Any
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering
from dotenv import load_dotenv
import sys
import re  # Importato qui per pulizia

# Add parent directory to path to import modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.prompts_config import REDUNDANCY_SYSTEM_PROMPT, get_redundancy_user_prompt
from llm_provider import llm_chat

# Load environment variables
load_dotenv()

class RedundancyEliminator:
    def __init__(self, embedding_model_name: str = None):
        """
        Initialize the Redundancy Eliminator.
        """
        if embedding_model_name is None:
            embedding_model_name = os.getenv("EMBEDDING_MODEL", "paraphrase-multilingual-MiniLM-L12-v2")
        
        print(f"Initializing Redundancy Eliminator...")
        self.embedding_model = SentenceTransformer(embedding_model_name)
        print(f"Embedding model loaded: {embedding_model_name}")

    def compute_embeddings(self, texts: List[str]) -> np.ndarray:
        """
        Compute embeddings for a list of texts.
        """
        return self.embedding_model.encode(texts, show_progress_bar=True)

    def group_similar_requirements(self, requirements: List[Dict[str, Any]], threshold: float = 0.85) -> List[List[Dict[str, Any]]]:
        """
        Group requirements using Hierarchical Agglomerative Clustering.
        """
        if not requirements:
            return []

        # 1. Calcolo Embeddings
        req_texts = [r.get('requirement', '') for r in requirements]
        embeddings = self.compute_embeddings(req_texts)
        
        # 2. Calcolo Matrici
        cosine_sim_matrix = cosine_similarity(embeddings)
        distance_matrix = 1 - cosine_sim_matrix
        
        distance_threshold = 1 - threshold

        # 3. Clustering
        clustering = AgglomerativeClustering(
            n_clusters=None,
            metric='precomputed',
            linkage='average',
            distance_threshold=distance_threshold
        )
        
        clustering.fit(distance_matrix)
        
        # 4. Raggruppamento
        groups = {}
        for idx, label in enumerate(clustering.labels_):
            if label not in groups:
                groups[label] = []
            groups[label].append(requirements[idx])
            
        return list(groups.values())

    def merge_group(self, group: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Merge a group of requirements using LLM.
        Note: The 'rationale' generated by LLM remains internal and is not exposed in output.
        """
        if len(group) == 1:
            return group[0]
            
        print(f"   Merging group of {len(group)} requirements...")
        
        system_prompt = REDUNDANCY_SYSTEM_PROMPT
        user_prompt = get_redundancy_user_prompt(group)
        
        model_name = os.getenv("LLM_MAPPING_MODEL", "deepseek-r1:14b") 
        print(f"   Using model: {model_name}")
        
        try:
            response = llm_chat(
                model=model_name,
                messages=[
                    {'role': 'system', 'content': system_prompt},
                    {'role': 'user', 'content': user_prompt}
                ],
                options={
                    "temperature": 0.1,
                    "num_predict": 2048
                }
            )
            
            response_text = response.get("message", {}).get("content", "").strip()
            
            # Extract JSON
            json_match = re.search(r'\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}', response_text, re.DOTALL)
            
            if json_match:
                result = json.loads(json_match.group(0))
                
                if result.get('is_merged'):
                    sources = []
                    chunks = []
                    original_reqs = []
                    
                    for req in group:
                        sources.append(req.get('source_file', ''))
                        chunks.append(str(req.get('source_chunk', '')))
                        original_reqs.append(req.get('requirement', ''))
                    
                    # 
                    # Qui costruiamo l'oggetto finale SENZA il campo 'rationale'
                    return {
                        'requirement': result['merged_requirement'],
                        'audit_question': result['audit_question'],
                        'source_file': ', '.join(sorted(list(set(sources)))), 
                        'source_chunk': ', '.join(sorted(list(set(chunks)))),
                        'original_count': len(group),
                        'traceability': original_reqs
                        # RIMOSSO: 'merge_rationale': result.get('rationale')
                    }
                else:
                    print("      LLM decided NOT to merge (is_merged=false). Keeping representative.")
                    return group[0] 
            else:
                print("      No valid JSON in merge response, keeping first requirement.")
                return group[0]
                
        except Exception as e:
            print(f"      Error merging group: {e}")
            return group[0]

    def process(self, requirements: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Main process: Group -> Merge -> Return unique list.
        """
        print(f"\nStarting Redundancy Elimination on {len(requirements)} requirements...")
        
        # 1. Group similar requirements
        groups = self.group_similar_requirements(requirements)
        
        reduction_count = len(requirements) - len(groups)
        print(f"   Found {len(groups)} distinct clusters. Potential reduction: {reduction_count} requirements.")
        
        final_requirements = []
        
        # 2. Process each group
        for i, group in enumerate(groups, 1):
            if len(group) > 1:
                print(f"   Processing cluster {i}/{len(groups)} (size: {len(group)})...")
                merged_req = self.merge_group(group)
                final_requirements.append(merged_req)
            else:
                final_requirements.append(group[0])
                
        print(f"Redundancy elimination complete. Final count: {len(final_requirements)} (Reduced from {len(requirements)}).")
        return final_requirements